### ISSUE TITLE
pycd01-sp

### ISSUE THREAD

**Issue by chakay37** [nvbach91/4IZ278-2023-2024-LS#135]
###### **Stručný popis:**
Webová aplikace se bude jmenovat DReality a bude k nalezení na https://www.dreality.cz. Půjde o platformu, kde realitní kanceláře budou zveřejňovat své nabídky bydlení. Nabídky budou obsahovat mnoho informací pro zákazníka. Mezi ty základní patří např. jestli se jedná o dům nebo byt, adresu nebo cenu, Ale mohou i zjistit třeba počet parkovacích míst. Pro běžné uživatele bude hlavní stránka vypadat jako seznam těchto nabídek bydlení.
###### **Popis funkcionalit:**
1. Hlavní stránka zobrazující seznam nabídek bydlení.
1. Hledání nabídek podle adresy.
1. Filtrace nabídek podle značek.
1. Zobrazení jednotlivých nabídek a informací o nich.
1. Možnost uživatele kontaktovat realitní kancelář, aby požádal o rezervaci nabídky.
1. Možnost uživatele napsat zprávu přímo v aplikaci, která přijde jako email kanceláři.
1. Nutnost se registrovat a přihlásit, aby uživatel mohl kontaktovat kancelář, svými údaji.
###### **Výčet stránek:**
- Přihlášení
- Registrace
- Seznam nabídek
- Informace nabídky

###### **Architektura:**
- webový server: Apache
- back-end: PHP 8+
- databáze: MySQL
- návrhový vzor: MVC, Singleton
- front-end: HTML, CSS, Javascript
- připojení k databázi: na serveru pomocí PDO

###### **Procesní diagram:**

![Aspose Words 65acd6e5-0c89-4a03-8d9d-b00c18619457 001](https://github.com/nvbach91/4IZ278-2023-2024-LS/assets/35643092/c91dd094-3d66-4354-986f-919f8c159ffc)

###### **Usecase diagram:**

![Aspose Words 65acd6e5-0c89-4a03-8d9d-b00c18619457 002](https://github.com/nvbach91/4IZ278-2023-2024-LS/assets/35643092/afbc9261-0180-484b-8044-e2790444e398)

###### **Sekvenční diagram:**

![Aspose Words 65acd6e5-0c89-4a03-8d9d-b00c18619457 003](https://github.com/nvbach91/4IZ278-2023-2024-LS/assets/35643092/30ee32d8-d2a8-4e99-816c-0dace09ca49d)

###### **Wireframe:**
Odkaz na wireframe: (Kvůli velkému scalu chybí tlačítko na prihlášení a registraci. Také značky na nabídce)

<https://www.figma.com/file/J0Sg4RNDGWoxvSpgNucBju/DReality?type=design&node-id=0%3A1&mode=design&t=r16rMa41WyLoWkJj-1>

![Aspose Words 65acd6e5-0c89-4a03-8d9d-b00c18619457 004](https://github.com/nvbach91/4IZ278-2023-2024-LS/assets/35643092/85c89906-d66a-46fb-ad65-2ffcd5d42e05)

###### **Schéma databáze:**
Odkaz na database diagram:[ https://www.dbdiagram.io/d/6613f1ed03593b6b6178cdbe](https://www.dbdiagram.io/d/6613f1ed03593b6b6178cdbe "https://www.dbdiagram.io/d/6613f1ed03593b6b6178cdbe")

![Aspose Words 65acd6e5-0c89-4a03-8d9d-b00c18619457 005](https://github.com/nvbach91/4IZ278-2023-2024-LS/assets/35643092/bd5f29e7-e8ec-4d4f-a974-52de468470b3)

**Comment by nvbach91** [comment]
- ve kterem kroku vytvorite novy zaznam v tabulce `homecustomers` a co to znamena?
- da se ze zadane adresy zjistit polohu nemovitosti na mape?
- lze pridat filtraci podle RK?
- co znamena znacka (tag) a k cemu to slouzi, jsou to jako pridavne charakteristiky nemovitosti?

**Comment by nvbach91** [comment]
https://github.com/nvbach91/4IZ278-2023-2024-LS/issues/139
